# Generated by Django 2.2.3 on 2020-03-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='bitmap',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
