# Generated by Django 2.2.3 on 2020-03-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('size', models.IntegerField(default=10)),
                ('url', models.URLField()),
                ('cooldown', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name_plural': 'Canvas',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User'},
        ),
    ]
