# Generated by Django 2.2.3 on 2020-03-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourplace', '0002_canvas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='url',
        ),
    ]
