# Generated by Django 2.2.3 on 2020-03-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourplace', '0002_auto_20200313_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
