# Generated by Django 3.0.4 on 2020-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourplace', '0003_auto_20200314_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
